export const LOGIN_ADMIN_REQUIEST = 'LOGIN_ADMIN_REQUIEST'
export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS'
export const LOGIN_ADMIN_FAIL = 'LOGIN_ADMIN_FAIL'
export const CLEAR_ERROR = 'CLEAR_ERROR'